export const columns = [
    { field: "destinacao", header: "Destino" },
    { field: "responsavel", header: "Responsavel" },
    { field: "data_entrada", header: "Data de Entrada" },
    { field: "convenio", header: "Convenio" },
    { field: "grupo", header: "Grupo" },
    { field: "layout", header: "Layout" },
    { field: "solicitante", header: "Solicitante" },
    { field: "robo", header: "Robo" },
    { field: "quantidade", header: "Quantidade" },
    { field: "margem_pma", header: "Margem Pma" },
    { field: "higienizado", header: "Higienizado" },
    { field: "origem", header: "Origem" },
    { field: "nome_lote", header: "Nome Lote" },
    { field: "dados_bancarios", header: "Dados Bancarios" },
    { field: "observacao", header: "Observacao" },
    { field: "data_inativacao", header: "Data da Inativacao" },
    { field: "status_base", header: "Status da Base" },
    { field: "variavel", header: "Variavel" },
    { field: "taxa_entrega", header: "Taxa da Entrega" },
    { field: "valor", header: "Valor" },
    { field: "texto", header: "Texto" },
    { field: "data_criacao", header: "Data Criação" },
]